# This file was generated by GoReleaser. DO NOT EDIT.
cask "caesar-search" do
  version "0.1.0"

  on_macos do
    on_intel do
      sha256 "3b3614d51dfd6db9e3b108b50f5b588764d9f48401f7e79150c713a24ebf58e5"
      url "https://github.com/caesar-data/caesar-search-cli/releases/download/v#{version}/caesar-search_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "60965df2fed72b951b40a960c02f286d34f946707a061b099ee26fd78f5ef320"
      url "https://github.com/caesar-data/caesar-search-cli/releases/download/v#{version}/caesar-search_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "35d0110fe841f8ae2e68b38fbdd858ea4b83193b84cc898d515771cea6b728fb"
      url "https://github.com/caesar-data/caesar-search-cli/releases/download/v#{version}/caesar-search_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "02956930c98f3f6182de90d48642ee450698edad88006c9256fffd4f218370f8"
      url "https://github.com/caesar-data/caesar-search-cli/releases/download/v#{version}/caesar-search_#{version}_linux_arm64.tar.gz"
    end
  end

  name "caesar-search"
  desc "CLI for the Caesar search API"
  homepage "https://github.com/caesar-data/caesar-search-cli"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "caesar-search"

  # No zap stanza required

end
