# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class CaesarSearch < Formula
  desc "CLI for the Caesar search API"
  homepage "https://github.com/caesar-data/caesar-search-cli"
  version "0.1.1"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/caesar-data/caesar-search-cli/releases/download/v0.1.1/caesar-search_0.1.1_darwin_amd64.tar.gz"
      sha256 "1e22f469eedf3ffa1f7f3af938eaffd1805b4faea926bc463e344b1395dada3f"

      define_method(:install) do
        bin.install "caesar-search"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/caesar-data/caesar-search-cli/releases/download/v0.1.1/caesar-search_0.1.1_darwin_arm64.tar.gz"
      sha256 "735d825bfb4a00ee07b04da9cccd6ca12956f4d5eb8433fe931a3ea8cf8da4dc"

      define_method(:install) do
        bin.install "caesar-search"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/caesar-data/caesar-search-cli/releases/download/v0.1.1/caesar-search_0.1.1_linux_amd64.tar.gz"
      sha256 "c0480e9a8d62dfd5d21215d91b898f489475198abe041f151bd6eb66ecb7bc5b"
      define_method(:install) do
        bin.install "caesar-search"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/caesar-data/caesar-search-cli/releases/download/v0.1.1/caesar-search_0.1.1_linux_arm64.tar.gz"
      sha256 "59a213be7a5ff4d1f8589fa62f391f1c77858ebf8e0df2de4c9818195539a0c2"
      define_method(:install) do
        bin.install "caesar-search"
      end
    end
  end

  test do
    assert_match "caesar-search", shell_output("#{bin}/caesar-search --version")
  end
end
