# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class CaesarSearch < Formula
  desc "CLI for the Caesar search API"
  homepage "https://github.com/caesar-data/caesar-search-cli"
  version "0.3.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/caesar-data/caesar-search-cli/releases/download/v0.3.0/caesar-search_0.3.0_darwin_amd64.tar.gz"
      sha256 "85d9a7c39f4e20299451f2fe7538b4b0fcae7ce9e890d3840a031ef43e55ff68"

      define_method(:install) do
        bin.install "caesar-search"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/caesar-data/caesar-search-cli/releases/download/v0.3.0/caesar-search_0.3.0_darwin_arm64.tar.gz"
      sha256 "0f068644325436e149e6651f39ad0eb90d1deac7bed1a4c5fff33ddf76d5b565"

      define_method(:install) do
        bin.install "caesar-search"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/caesar-data/caesar-search-cli/releases/download/v0.3.0/caesar-search_0.3.0_linux_amd64.tar.gz"
      sha256 "7fcca5486f46f067228b29ebcd97577b3d8590964aff99f66e371a2734d4b5a0"
      define_method(:install) do
        bin.install "caesar-search"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/caesar-data/caesar-search-cli/releases/download/v0.3.0/caesar-search_0.3.0_linux_arm64.tar.gz"
      sha256 "52500bf8e85e2dd1f6b4334045ff25a6cef16b3cd6346875aad4b4de0a3113f9"
      define_method(:install) do
        bin.install "caesar-search"
      end
    end
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/caesar-search --version")
  end
end
